import Foundation
import FindDiskKillerCore

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"
    case japanese = "ja"
    case korean = "ko"
    case german = "de"
    case french = "fr"
    case spanish = "es"
    case brazilianPortuguese = "pt-BR"
    case russian = "ru"

    var id: String { rawValue }

    var localeIdentifier: String {
        switch self {
        case .system: L10n.preferredLanguage.localeIdentifier
        default: rawValue
        }
    }

    var localizedName: String {
        switch self {
        case .system: L10n.text("跟随系统")
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        case .japanese: "日本語"
        case .korean: "한국어"
        case .german: "Deutsch"
        case .french: "Français"
        case .spanish: "Español"
        case .brazilianPortuguese: "Português (Brasil)"
        case .russian: "Русский"
        }
    }
}

extension SampleRange {
    var localizedTitle: String { L10n.text(rawValue) }
}

extension HistoryRetention {
    var localizedTitle: String {
        switch self {
        case .sevenDays: L10n.text("7 天")
        case .thirtyDays: L10n.text("30 天")
        case .oneYear: L10n.text("1 年")
        }
    }

    var localizedAnalysisTitle: String {
        switch self {
        case .sevenDays: L10n.text("近 7 天分析")
        case .thirtyDays: L10n.text("近 30 天分析")
        case .oneYear: L10n.text("近 1 年分析")
        }
    }
}

extension ProcessActivity {
    var localizedDisplayName: String {
        let marker = "（可能关联）"
        guard name.hasSuffix(marker) else { return name }
        return String(name.dropLast(marker.count)) + L10n.text(marker)
    }
}

enum L10n {
    static var selectedLanguage: AppLanguage {
        let rawValue = UserDefaults.standard.string(forKey: "appLanguage") ?? AppLanguage.system.rawValue
        return AppLanguage(rawValue: rawValue) ?? .system
    }

    static var preferredLanguage: AppLanguage {
        let identifier = Locale.preferredLanguages.first?.lowercased() ?? "en"
        if identifier.hasPrefix("zh-hant") || identifier.hasPrefix("zh-tw")
            || identifier.hasPrefix("zh-hk") { return .traditionalChinese }
        if identifier.hasPrefix("zh") { return .simplifiedChinese }
        if identifier.hasPrefix("ja") { return .japanese }
        if identifier.hasPrefix("ko") { return .korean }
        if identifier.hasPrefix("de") { return .german }
        if identifier.hasPrefix("fr") { return .french }
        if identifier.hasPrefix("es") { return .spanish }
        if identifier.hasPrefix("pt") { return .brazilianPortuguese }
        if identifier.hasPrefix("ru") { return .russian }
        return .english
    }

    static var effectiveLanguage: AppLanguage {
        selectedLanguage == .system ? preferredLanguage : selectedLanguage
    }

    static func text(_ key: String) -> String {
        text(key, language: effectiveLanguage)
    }

    static func text(_ key: String, language: AppLanguage) -> String {
        let resolvedLanguage = language == .system ? preferredLanguage : language
        let localized = languageBundle(for: resolvedLanguage)
            .localizedString(forKey: key, value: key, table: nil)
        guard localized == key, resolvedLanguage != .simplifiedChinese else {
            return localized
        }
        return recentEnglishFallbacks[key]
            ?? historyEnglishFallbacks[key]
            ?? storageMapEnglishFallbacks[key]
            ?? localized
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(
            format: text(key),
            locale: Locale(identifier: effectiveLanguage.localeIdentifier),
            arguments: arguments
        )
    }

    static func format(_ key: String, arguments: [String]) -> String {
        format(key, arguments: arguments, language: effectiveLanguage)
    }

    static func format(
        _ key: String,
        arguments: [String],
        language: AppLanguage
    ) -> String {
        let resolvedLanguage = language == .system ? preferredLanguage : language
        return String(
            format: text(key, language: resolvedLanguage),
            locale: Locale(identifier: resolvedLanguage.localeIdentifier),
            arguments: arguments.map { $0 as NSString }
        )
    }

    static func date(
        _ value: Date,
        date: Date.FormatStyle.DateStyle,
        time: Date.FormatStyle.TimeStyle
    ) -> String {
        value.formatted(
            Date.FormatStyle(date: date, time: time)
                .locale(Locale(identifier: effectiveLanguage.localeIdentifier))
        )
    }

    private static func languageBundle(for language: AppLanguage) -> Bundle {
        languageBundles[language.rawValue.lowercased()] ?? AppResourceBundle.value
    }

    private static let languageBundles: [String: Bundle] = {
        Dictionary(uniqueKeysWithValues: AppLanguage.allCases.compactMap { language in
            guard language != .system else { return nil }
            let resourceName = language.rawValue.lowercased()
            guard let path = AppResourceBundle.value.path(forResource: resourceName, ofType: "lproj"),
                  let bundle = Bundle(path: path) else {
                return nil
            }
            return (resourceName, bundle)
        })
    }()

    // Recently added surfaces use English as the common fallback until every
    // shipped locale receives a native translation. Non-Chinese interfaces
    // must never fall back to the Simplified Chinese lookup key itself.
    private static let recentEnglishFallbacks: [String: String] = [
        "%@ 以前的应用明细已精简": "Application details before %@ have been compacted",
        "%@ 本次有 %llu 条事件未能完整处理，列表可能遗漏。": "%@ %llu events could not be fully processed, so some entries may be missing.",
        "%@ 次事件": "%@ events",
        "Claude SDK 未确认 session 已删除": "Claude SDK could not confirm that the session was deleted",
        "Claude SDK 版本不兼容": "The Claude SDK version is incompatible",
        "继续清理": "Continue Cleaning",
        "Docker Volume · 通过 Docker 命令删除": "Docker Volume · Deleted with Docker",
        "Docker 容器 · 通过 Docker 命令删除": "Docker Container · Deleted with Docker",
        "Docker 镜像 · 通过 Docker 命令删除": "Docker Image · Deleted with Docker",
        "Node.js 运行时安装失败：%@": "Node.js runtime installation failed: %@",
        "Node.js 运行时验证失败：%@": "Node.js runtime validation failed: %@",
        "OpenCode 官方清理入口已不可用": "The official OpenCode cleanup command is no longer available",
        "OpenCode 数据目录不是官方默认目录": "The OpenCode data directory is not an official default location",
        "OpenCode 未确认 session 已删除": "OpenCode could not confirm that the session was deleted",
        "Podman Volume · 通过 Podman 命令删除": "Podman Volume · Deleted with Podman",
        "Podman 容器 · 通过 Podman 命令删除": "Podman Container · Deleted with Podman",
        "Podman 镜像 · 通过 Podman 命令删除": "Podman Image · Deleted with Podman",
        "Worktree · 保留主仓库": "Worktree · Main Repository Preserved",
        "上级目录 · %@": "Parent Folder · %@",
        "下载或验证失败": "Download or Verification Failed",
        "不完整": "Incomplete",
        "中止当前空间扫描": "Stop the Current Storage Scan",
        "中止本次扫描": "Stop This Scan",
        "为了避免显示看似精确但含义错误的结果，本次追踪已停止。": "Tracing stopped to avoid presenting precise-looking but misleading results.",
        "主仓库 · 整个目录移入废纸篓": "Main Repository · Move Entire Folder to Trash",
        "主仓库仍有关联的 Worktree，请先移除这些 Worktree 后再删除主仓库。": "The main repository still has linked worktrees. Remove them before deleting the main repository.",
        "停止本次扫描": "Stop This Scan",
        "元数据访问": "Metadata Accesses",
        "删除尚未安装的模拟器运行时下载包": "Delete downloaded Simulator runtimes that are not installed",
        "压缩后约 %@ – %@": "Approximately %@ – %@ after compression",
        "可重建缓存 · 移入废纸篓后自动重建目录": "Rebuildable Cache · Folder Recreated After Moving to Trash",
        "官方 Claude SDK 清理组件不可用": "The official Claude SDK cleanup component is unavailable",
        "官方 Codex 清理入口已不可用": "The official Codex cleanup command is no longer available",
        "官方服务的数据目录与扫描来源不一致": "The official service data directory does not match the scanned source",
        "官方清理协议不兼容": "The official cleanup protocol is incompatible",
        "官方清理服务响应超时": "The official cleanup service timed out",
        "将删除超出 %@ 的聚合数据，此操作无法撤销。": "Aggregated data beyond %@ will be deleted. This cannot be undone.",
        "将整个主仓库移入废纸篓；不会删除同目录下的其它仓库": "Move the entire main repository to Trash without deleting other repositories in the same folder",
        "展开子代理": "Expand Subagents",
        "开始后会进行短时系统级文件访问追踪，只显示命中此卷的事件。": "A short system-level file access trace will begin and show only events that reach this volume.",
        "当前 OpenCode 不支持官方 session 删除": "This OpenCode version does not support official session deletion",
        "当前占用 %@。降至 %@ 后，较早的应用趋势和日排名可能并入“其他”且无法恢复；若仍无法满足预算，历史保存会暂停。": "Current usage is %@. Reducing it to %@ may permanently merge older application trends and daily rankings into Other. History saving will pause if the budget still cannot be met.",
        "当前系统输出格式无法可靠解析，没有生成访问来源结果。": "The current system output could not be parsed reliably, so no access-source results were produced.",
        "当前采样存在计数缺口；可用指标仍按实测展示，缺失指标不会以零值参与判断。": "The current sample has counting gaps. Available metrics still show measured values, and missing metrics are never treated as zero.",
        "所选目录不是可识别的 Codex、Claude Code 或 OpenCode 数据位置": "The selected folder is not a recognized Codex, Claude Code, or OpenCode data location",
        "折叠子代理": "Collapse Subagents",
        "操作": "Operation",
        "文件身份已变化": "File identity changed",
        "无法确认文件是否正在写入": "Unable to determine whether the file is being written",
        "无法确认活动状态": "Unable to determine activity status",
        "更新空间占用": "Update Storage Usage",
        "最早访问来源": "Earliest Access Sources",
        "未安装运行时下载包 · 移入废纸篓": "Uninstalled Runtime Download · Move to Trash",
        "未找到 OpenCode 官方清理命令": "The official OpenCode cleanup command was not found",
        "未找到兼容的官方清理入口": "No compatible official cleanup command was found",
        "本机安装": "Installed on This Mac",
        "模拟器设备 · 通过 Xcode Simulator 删除": "Simulator Device · Deleted with Xcode Simulator",
        "模拟器运行时 · 通过 Xcode Simulator 删除": "Simulator Runtime · Deleted with Xcode Simulator",
        "正在准备应用分析": "Preparing App Analysis",
        "正在准备清理项目": "Preparing Cleanup Items",
        "正在准备资源明细": "Preparing Resource Details",
        "重试同步": "Retry Sync",
        "正在安装官方运行时…": "Installing the Official Runtime…",
        "正在校验官方运行时…": "Verifying the Official Runtime…",
        "此 Claude 来源不支持安全清理": "This Claude source does not support safe cleanup",
        "此 Codex 来源不支持安全清理": "This Codex source does not support safe cleanup",
        "此 OpenCode 来源不支持安全清理": "This OpenCode source does not support safe cleanup",
        "此来源暂不支持安全清理": "This source does not currently support safe cleanup",
        "添加": "Add",
        "移除这个 Worktree，并保留主仓库": "Remove this worktree and preserve the main repository",
        "等待访问": "Waiting for Access",
        "等待这个卷出现访问事件": "Waiting for an access event on this volume",
        "结果表示追踪期间最早观察到的卷访问，不等同于硬盘盒物理唤醒的绝对证明。": "Results show the earliest observed volume access during tracing and do not prove the exact physical wake time of the drive enclosure.",
        "聊天仍在活动": "The chat is still active",
        "能力检查尚未完成": "Capability check is not complete",
        "自动（%@）": "Automatic (%@)",
        "访问时间线": "Access Timeline",
        "证据": "Evidence",
        "请在 Claude Desktop 中删除": "Delete this in Claude Desktop",
        "请求读 / 写": "Requested Read / Write",
        "读 / 写": "Read / Write",
        "路径": "Path",
        "还没有命中的访问记录": "No matching access events yet",
        "进程 ID %d · %@ 次事件": "Process ID %d · %@ events",
        "追踪访问来源": "Trace Access Sources",
        "选择 AI Agent 数据位置": "Choose an AI Agent Data Location",
        "选择此资源进行清理": "Select this resource for cleanup",
        "通过 Podman 删除此已停止容器": "Delete this stopped container with Podman",
        "通过 Podman 删除此未被容器引用的 Volume": "Delete this volume, which is not referenced by any container, with Podman",
        "通过 Podman 删除此镜像；执行前会再次检查容器引用": "Delete this image with Podman after checking container references again",
        "通过 Xcode Simulator 删除此设备及其数据": "Delete this device and its data with Xcode Simulator",
        "通过 Xcode Simulator 删除此运行时": "Delete this runtime with Xcode Simulator",
        "部分指标暂不可用": "Some Metrics Are Temporarily Unavailable",
        "重新分析空间地图": "Analyze Storage Map Again",
        "重新扫描已识别的应用、工具和数据位置": "Rescan recognized apps, tools, and data locations",
        "首次": "First",
        "首次观察": "First Observed"
    ]

    // New history surfaces fall back to English until each existing localization
    // receives a native translation; this avoids mixed Chinese UI in non-Chinese locales.
    private static let historyEnglishFallbacks: [String: String] = [
        "复核永久删除": "Review Permanent Deletion",
        "清理结果": "Cleanup Results",
        "正在核验官方能力与聊天活动状态": "Checking official capabilities and chat activity",
        "%d 个聊天可安全提交给官方清理": "%d chats can be safely submitted for official cleanup",
        "正在串行提交；可取消尚未开始的聊天": "Submitting one at a time; unstarted chats can be cancelled",
        "成功 %d · 跳过 %d · 失败 %d": "%d succeeded · %d skipped · %d failed",
        "预计立即释放": "Estimated Immediate Release",
        "逻辑清理": "Logical Cleanup",
        "保留数据": "Retained Data",
        "由官方接口永久删除": "Permanently Deleted by Official APIs",
        "操作不可撤销。活动聊天、身份变化或协议不兼容会立即跳过；不会改写数据库，也不会降级为手工删除文件。": "This cannot be undone. Active chats, identity changes, and incompatible protocols are skipped. Databases are never rewritten, and file deletion is never used as a fallback.",
        "操作不可撤销。活动聊天或身份变化会立即跳过；官方执行器失败时会自动切换，不会改写数据库，也不会降级为手工删除文件。": "This cannot be undone. Active chats and identity changes are skipped. Failed official runtimes are switched automatically; databases are never rewritten, and file deletion is never used as a fallback.",
        "未找到 Codex 官方执行器": "No Official Codex Runtime Found",
        "Codex 官方执行器启动失败": "Official Codex Runtime Failed to Start",
        "Codex 官方服务的数据目录与扫描来源不一致": "The official Codex service data directory does not match the scanned source",
        "Codex 官方清理服务响应超时": "Official Codex Cleanup Timed Out",
        "Codex 官方服务返回了无效响应": "The official Codex service returned an invalid response",
        "Codex 官方删除调用失败": "Official Codex Delete Call Failed",
        "Codex 聊天身份或父子关系已变化": "The Codex chat identity or parent relationship changed",
        "所有 Codex 官方执行器均失败：%@": "All official Codex runtimes failed: %@",
        "正在逐项核验…": "Checking each chat…",
        "打开 Claude": "Open Claude",
        "已删除": "Deleted",
        "已取消": "Cancelled",
        "核验中": "Checking",
        "可安全删除": "Safe to Delete",
        "活动中，跳过": "Active, Skipped",
        "数据已变化，跳过": "Data Changed, Skipped",
        "实际复核释放 %@": "Actually Released After Verification: %@",
        "数据库逻辑删除不会计入立即释放；不会执行 VACUUM 或 checkpoint。": "Logical database cleanup is not counted as immediate release. VACUUM and checkpoints are never run.",
        "取消剩余任务": "Cancel Remaining",
        "永久删除": "Delete Permanently",
        "7 天": "7 Days",
        "30 天": "30 Days",
        "1 年": "1 Year",
        "近 7 天分析": "7-Day Analysis",
        "近 30 天分析": "30-Day Analysis",
        "近 1 年分析": "1-Year Analysis",
        "上一周期数据不足；当前结论仅基于已覆盖时间，不会用零值补齐缺口。": "The previous period has insufficient data. Findings use only covered time and never fill gaps with zeroes.",
        "不会保存文件路径、PID、逐秒样本或深度追踪记录。": "File paths, PIDs, per-second samples, and deep trace records are not saved.",
        "主要应用": "Leading Applications",
        "导出包含聚合资源统计和应用名称；请选择可信的位置。": "The export contains aggregate resource statistics and application names. Choose a trusted location.",
        "仅在本机保存聚合数据；每分钟批量写入一次，分钟明细保留 24 小时。": "Aggregated data stays on this Mac and is written once per minute. Minute detail is kept for 24 hours.",
        "保存应用级活动": "Save Application Activity",
        "保存监测历史": "Save Monitoring History",
        "保留时间": "Retention",
        "写入 %@": "Write %@",
        "写入占比": "Write Share",
        "峰值 CPU": "Peak CPU",
        "数据覆盖": "Data Coverage",
        "数据覆盖 %.0f%%，共 %d 个数据点": "Data coverage %.0f%% across %d data points",
        "刷新分析": "Refresh Analysis",
        "历史保存正常": "History Saving Normally",
        "历史保存已关闭": "History Saving Off",
        "历史数据库不可用": "History Database Unavailable",
        "取消": "Cancel",
        "周期观察": "Period Findings",
        "在设置中开启后，聚合数据将每分钟保存一次且只留在本机。": "Enable history in Settings to save local aggregate data once per minute.",
        "完成第一个分钟汇总后，这里会出现趋势和应用排名。": "Trends and application rankings appear after the first minute is summarized.",
        "实时会话": "Live Session",
        "实时曲线仍只保留在内存中，退出应用后自动清除。": "Live charts remain in memory and are cleared when the app quits.",
        "尚未保存": "Not Saved Yet",
        "尚未保存监测历史": "No Monitoring History Yet",
        "已暂停历史保存": "History Saving Paused",
        "平均 CPU": "Average CPU",
        "当前仅保存整机与设备聚合。": "Only system and device aggregates are currently saved.",
        "所有历史分析数据和应用排名将被永久删除，实时监测不受影响。": "All history data and application rankings will be permanently deleted. Live monitoring is unaffected.",
        "已有历史可在停止保存后继续查看；删除后无法恢复。": "Saved history remains available after recording stops. Deletion cannot be undone.",
        "打开数据设置": "Open Data Settings",
        "在 Finder 中显示数据文件": "Show Data File in Finder",
        "历史分析": "History",
        "导出 CSV": "Export CSV",
        "导出 PDF": "Export PDF",
        "导出历史分析": "Export History",
        "无法导出历史分析": "Unable to Export History",
        "趋势指标": "Trend Metric",
        "CPU 活动趋势": "CPU Activity Trend",
        "网络活动趋势": "Network Activity Trend",
        "连续区间": "Continuous Interval",
        "接收": "Received",
        "发送": "Sent",
        "缺失时段会断开显示，不会按零值补齐。": "Missing intervals are shown as gaps and are never filled with zeroes.",
        "当前周期数据覆盖不足 70%，暂不生成与上一周期的比较结论。": "Coverage is below 70%, so no comparison with the previous period is generated.",
        "好": "OK",
        "分析周期": "Analysis Period",
        "指标": "Metric",
        "按写入总量排序": "Sorted by Total Writes",
        "接近上限": "Nearing Limit",
        "接近空间上限": "Nearing Storage Limit",
        "数据覆盖 %.0f%%": "Data Coverage %.0f%%",
        "无法读取历史分析": "Unable to Load History",
        "最大占用": "Maximum Storage",
        "最近保存": "Last Saved",
        "本地占用": "Local Storage",
        "本地空间": "Local Storage",
        "正在优化 %.0f%%": "Optimizing %.0f%%",
        "正在优化历史": "Optimizing History",
        "正在加载历史分析": "Loading History",
        "正在积累历史数据": "Building History",
        "正常": "Normal",
        "清除历史": "Clear History",
        "清除实时会话数据": "Clear Live Session Data",
        "清除已保存历史": "Clear Saved History",
        "清除已保存历史？": "Clear Saved History?",
        "仅停止保存": "Stop Saving Only",
        "停止保存监测历史？": "Stop Saving Monitoring History?",
        "停止并删除已有历史": "Stop and Delete Saved History",
        "物理写入": "Physical Writes",
        "物理写入与上一周期基本持平。": "Physical writes are essentially unchanged from the previous period.",
        "物理写入较上一周期减少 %.0f%%。": "Physical writes decreased %.0f%% from the previous period.",
        "物理写入较上一周期增加 %.0f%%。": "Physical writes increased %.0f%% from the previous period.",
        "物理读取": "Physical Reads",
        "登录后打开主窗口": "Open Main Window After Login",
        "监测历史": "Monitoring History",
        "磁盘活动趋势": "Disk Activity Trend",
        "等待首个分钟汇总": "Waiting for First Minute Summary",
        "缩短保留时间？": "Shorten Retention?",
        "缩短并删除": "Shorten and Delete",
        "网络传输": "Network Transfer",
        "读取 %@": "Read %@",
        "达到预算并暂停": "Budget Reached and Paused",
        "这个周期还没有应用级活动。": "There is no application activity for this period yet.",
        "选定时间": "Selected Time",
        "部分明细已精简": "Some Detail Was Compacted",
        "降低并优化": "Lower and Optimize",
        "降低最大占用？": "Lower Maximum Storage?",
        "预计占用": "Estimated Storage",
        "其他": "Other",
        "软件更新": "Software Update",
        "设置类别": "Settings Category",
        "当前无法检查更新": "Unable to check for updates right now",
        "当前构建尚未配置软件更新": "Software updates are not configured in this build",
        "当前构建缺少有效的 Sparkle 公钥": "This build is missing a valid Sparkle public key",
        "当前构建缺少有效的更新地址": "This build is missing a valid update feed URL",
        "正在检查或安装更新": "An update check or installation is in progress",
        "正在确认追踪已结束，请稍后重试": "Confirming that tracing has stopped. Try again shortly.",
        "结束追踪后可检查更新": "Stop tracing before checking for updates",
        "请先将 FindDiskKiller 移到“应用程序”文件夹": "Move FindDiskKiller to Applications first",
        "官网": "Official Website",
        "了解产品能力、隐私设计与常见问题，并下载签名和公证的正式版本。": "Explore features, privacy design, and common questions, and download signed, notarized releases.",
        "查看源代码和版本记录，并反馈问题。": "View the source and release history, or report an issue.",
        "更多信息": "More Information",
        "在默认浏览器中打开": "Open in the default browser",
        "复制链接": "Copy Link",
        "无法打开默认浏览器，你可以复制链接后重试。": "The default browser could not be opened. Copy the link and try again.",
        "自动检查更新": "Automatically Check for Updates",
        "每天最多检查一次；不会上传监测数据。": "Checks at most once per day and never uploads monitoring data.",
        "当前版本": "Current Version",
        "检查更新…": "Check for Updates…",
        "正在检查": "Checking",
        "查看追踪组件": "View Trace Component",
        "关于 FindDiskKiller": "About FindDiskKiller",
        "设置…": "Settings…",
        "已有追踪正在运行或结束中，请稍后重试": "Another trace is running or stopping. Try again shortly.",
        "正在检查或安装更新，请稍后再开始追踪": "An update is in progress. Start tracing after it finishes.",
        "正在停止追踪": "Stopping Trace",
        "正在确认追踪已结束": "Confirming Trace Has Stopped",
        "仍可检查更新；如需安装，将在追踪完全停止后自动继续。": "You can still check for updates. Installation will continue automatically after tracing fully stops.",
        "仍可检查更新；确认后台追踪结束前不会开始安装。": "You can still check for updates. Installation will not start until background tracing is confirmed stopped.",
        "Claude 官方清理": "Official Claude Cleanup",
        "选择并清理": "Select and Clean",
        "直接在当前列表中选择聊天": "Select chats directly in the current list",
        "已选 %d 项": "%d Selected",
        "退出选择": "Exit Selection",
        "清理计划": "Cleanup Plan",
        "直接勾选左侧聊天，无需再次选择": "Check chats on the left; no second selection step is required.",
        "选择要清理的聊天": "Select Chats to Clean",
        "勾选后，这里会实时汇总可验证文件与预计释放空间。": "Your selection will appear here with verified files and estimated reclaimable space.",
        "最终提交前会再次核验活动状态和官方清理能力。": "Activity and official cleanup support are revalidated before deletion.",
        "已测量": "Measured",
        "保留在磁盘": "Retained on Disk",
        "可验证文件构成": "Verified File Breakdown",
        "选择后计算可由官方方式验证的文件": "Select chats to calculate files verifiable through official cleanup.",
        "会话文件": "Session Files",
        "工具结果": "Tool Results",
        "子代理文件": "Subagent Files",
        "文件历史": "File History",
        "附件": "Attachments",
        "快照": "Snapshots",
        "任务": "Tasks",
        "工作流": "Workflows",
        "其它文件": "Other Files",
        "Node.js 运行时": "Node.js Runtime",
        "运行时位置": "Runtime Location",
        "批量清理 Claude Code 聊天时，需要 Node.js 运行 Anthropic 官方 SDK；会自动复用本机已安装的 Node.js 20 或更高版本。": "Batch-cleaning Claude Code chats requires Node.js to run the official Anthropic SDK. A locally installed Node.js 20 or later is reused automatically.",
        "下载 Node.js v%@": "Download Node.js v%@",
        "重新检测": "Check Again",
        "正在下载并校验官方运行时…": "Downloading and verifying the official runtime…",
        "正在下载官方运行时…": "Downloading the official runtime…",
        "正在校验运行时…": "Verifying the runtime…",
        "正在安装运行时…": "Installing the runtime…",
        "检测中…": "Checking…",
        "未检测到可用运行时": "No Usable Runtime Detected",
        "正在下载": "Downloading",
        "正在校验": "Verifying",
        "正在安装": "Installing",
        "下载失败": "Download Failed",
        "环境变量指定": "Set by Environment Variable",
        "旧版内置": "Bundled in Previous Version",
        "已下载": "Downloaded",
        "系统安装": "System Installation",
        "Node.js 运行时下载失败：%@": "Node.js runtime download failed: %@",
        "Node.js 运行时校验失败，已放弃安装": "Node.js runtime failed checksum verification, so installation was abandoned.",
        "Node.js 运行时解压失败：%@": "Node.js runtime extraction failed: %@",
        "归档中缺少 node 可执行文件": "The archive is missing the node executable",
        "tar 退出码非零": "tar exited with a non-zero status"
    ]

    private static let storageMapEnglishFallbacks: [String: String] = [
        "空间地图": "Storage Map",
        "刷新空间地图": "Refresh Storage Map",
        "返回空间地图": "Back to Storage Map",
        "返回 AI 工具": "Back to AI Tools",
        "全部": "All",
        "应用与浏览器": "Apps & Browsers",
        "开发工具": "Developer Tools",
        "容器": "Containers",
        "镜像": "Images",
        "独占 %@": "Unique %@",
        "共享 %@": "Shared %@",
        "总大小 %@": "Total %@",
        "%@ 个仓库引用": "%@ repository references",
        "%@ 个容器": "%@ containers",
        "容器引用未知": "Container references unknown",
        "被 %@ 个容器引用": "Referenced by %@ containers",
        "当前未被容器引用": "Not currently referenced by a container",
        "容器引用关系未知": "Container reference status unknown",
        "正在使用": "In Use",
        "未使用": "Not in Use",
        "%@ 项": "%@ items",
        "Docker Engine 报告，组间可能共享底层数据": "Docker Engine report; groups may share underlying data",
        "%@ 宿主机物理存储": "%@ Host Physical Storage",
        "%@ Engine 资源": "%@ Engine Resources",
        "Podman machine、容器层与宿主机状态": "Podman machines, container layers, and host state",
        "提供者报告的镜像、容器、Volume 与构建缓存；对象可能共享底层数据": "Provider-reported images, containers, volumes, and build cache; objects may share underlying data",
        "Docker Engine 容量报告不可用，已使用对象清单": "Docker Engine capacity report unavailable; using object inventory",
        "Podman 容量报告不可用，已使用对象清单": "Podman capacity report unavailable; using object inventory",
        "AI 工具": "AI Tools",
        "未知磁盘": "Unknown Volume",
        "默认目录": "Default Location",
        "环境变量": "Environment Variable",
        "已知客户端": "Known Client",
        "手动添加": "Added Manually",
        "嵌入式 Agent": "Embedded Agent",
        "已发现目录": "Discovered Location",
        "路径已隐藏": "Path Hidden",
        "%d 个路径指向同一位置": "%d paths point to the same location",
        "工作区": "Workspaces",
        "可进行仓库分析": "Repository Analysis Available",
        "进入详情后定位 Git 仓库与 Worktree": "Open details to locate Git repositories and worktrees",
        "所有仓库统一归入这一项": "All repositories are grouped into this single source",
        "在详情中分析": "Analyze in Details",
        "可分析": "Ready",
        "来源分类": "Source Category",
        "%d 个来源": "%d sources",
        "%d 个项目": "%d items",
        "安全清理": "Safe Cleanup",
        "可安全清理": "Safe to Clean",
        "可安全清理 %@": "%@ Safe to Clean",
        "查看可安全清理的缓存": "View caches that are safe to clean",
        "当前没有经过验证的可重建缓存": "No verified rebuildable caches are currently available",
        "仅包含可重建缓存；发生变化的项目会自动跳过。": "Only rebuildable caches are included. Changed items are skipped automatically.",
        "已选 %@": "%@ Selected",
        "选择 %@": "Select %@",
        "选择当前分类": "Select Current Category",
        "取消选择当前分类": "Deselect Current Category",
        "清理项目": "Cleanup Items",
        "展开清理项目": "Expand Cleanup Items",
        "收起清理项目": "Collapse Cleanup Items",
        "部分选择": "Partially Selected",
        "正在刷新": "Refreshing",
        "当前没有可安全清理的缓存": "No Caches Are Safe to Clean Right Now",
        "只有经过验证的可重建缓存才会显示在这里。": "Only verified rebuildable caches appear here.",
        "此分类没有可安全清理的缓存": "No Caches in This Category Are Safe to Clean",
        "切换到其他来源分类查看可清理项目。": "Switch to another source category to view cleanup items.",
        "查看开发环境如何使用磁盘空间": "See How Your Development Environment Uses Storage",
        "分析在本机完成，不读取源码、浏览记录或账户内容。新来源目前仅提供分析，不会执行清理命令。": "Analysis stays on this Mac and never reads source code, browsing history, or account content. New sources are analysis-only and never run cleanup commands.",
        "开始分析": "Start Analysis",
        "已发现 %d 个来源": "%d sources found",
        "来源": "Source",
        "文件分配占用": "File Allocation",
        "可回收证据": "Reclaimable Evidence",
        "状态": "Status",
        "查看详情": "View Details",
        "显示检查器": "Show Inspector",
        "选择一个来源": "Select a Source",
        "检查占用组成、数据质量与分析边界。": "Inspect storage composition, data quality, and analysis boundaries.",
        "正在查找已安装工具": "Finding Installed Tools",
        "正在发现本机存储来源": "Discovering Storage Sources on This Mac",
        "%d 个应用与工具已确认": "%d Apps and Tools Confirmed",
        "确认后立即加入下方列表，完成后自动开始分析。": "Confirmed sources appear below immediately. Analysis starts automatically when discovery finishes.",
        "刚刚确认": "Just Confirmed",
        "正在检查已知应用、工具与数据位置": "Checking Known Apps, Tools, and Data Locations",
        "发现仍在进行": "Discovery is still running",
        "已确认的应用与工具": "Confirmed Apps and Tools",
        "%d 个已确认": "%d Confirmed",
        "只读取位置，不读取文件内容": "Reads locations only, never file contents",
        "正在检查": "Checking",
        "正在识别应用数据、容器与代码仓库位置。": "Locating application data, containers, and code repositories.",
        "正在建立这台 Mac 的空间地图": "Building This Mac's Storage Map",
        "发现完成后会自动进入分析": "Analysis starts automatically when discovery finishes",
        "正在并行确认": "Checking in Parallel",
        "只读取位置与文件分配信息，不读取内容。": "Reading locations and file allocation only, never file contents.",
        "应用数据": "Application Data",
        "正在确认浏览器与应用位置": "Checking browser and application locations",
        "正在确认缓存与工具链位置": "Checking cache and toolchain locations",
        "容器环境": "Container Environments",
        "正在读取容器数据配置": "Reading container data configuration",
        "代码仓库": "Code Repositories",
        "正在识别仓库与 Worktree 关系": "Identifying repository and worktree relationships",
        "扫描位置确认中": "Confirming Scan Locations",
        "完整扫描代码仓库": "Complete Code Repository Scan",
        "授权一次后，桌面、文稿、下载与外接磁盘会统一纳入仓库识别。": "Authorize once to include Desktop, Documents, Downloads, and external volumes in repository discovery.",
        "打开完全磁盘访问": "Open Full Disk Access",
        "扫描仍会继续；完全磁盘访问仅用于补齐当前不可读的受保护目录。": "Scanning continues; Full Disk Access only adds protected locations that are currently unreadable.",
        "可读目录和外接磁盘会直接扫描；授权后可进一步识别受保护位置。": "Readable folders and external disks are scanned directly; access adds protected locations.",
        "检查授权": "Check Access",
        "正在检查授权": "Checking Access",
        "正在确认完全磁盘访问": "Confirming Full Disk Access",
        "尚未获得完全磁盘访问": "Full Disk Access Not Granted",
        "在系统设置中为 FindDiskKiller 开启权限，返回应用后会自动重新检查。": "Enable FindDiskKiller in System Settings. Access is checked again automatically when you return.",
        "未发现支持的来源": "No Supported Sources Found",
        "安装受支持的工具后重新探测。": "Install a supported tool, then detect again.",
        "安装受支持的工具后重新探测，或稍后添加工作区授权。": "Install a supported tool and detect again, or add an authorized workspace later.",
        "重新探测": "Detect Again",
        "增大窗口以查看空间地图": "Make the Window Wider to View Storage Map",
        "当前选择已保留。折叠侧栏可获得更多内容空间。": "Your selection is preserved. Collapse the sidebar for more content space.",
        "来源不可用": "Source Unavailable",
        "详情尚未就绪：%@": "Details aren't ready yet: %@",
        "AI 工具深度分析": "AI Tools Deep Analysis",
        "已分析空间": "Analyzed Storage",
        "已发现来源": "Discovered Sources",
        "更新失败，显示上次结果": "Update Failed, Showing Previous Results",
        "停止分析": "Stop Analysis",
        "等待你开始只读分析": "Waiting for you to start read-only analysis",
        "%d 个来源 · 更新于 %@": "%d sources · Updated %@",
        "正在停止…": "Stopping…",
        "正在确认扫描范围": "Confirming Scan Scope",
        "正在读取文件分配": "Reading File Allocation",
        "正在核对跨来源归属": "Reconciling Cross-Source Ownership",
        "正在提交结果": "Committing Results",
        "正在等待整体分析结果": "Waiting for the Full Analysis",
        "正在同步最新状态": "Syncing the Latest State",
        "正在定位 Git 仓库与 Worktree": "Locating Git Repositories and Worktrees",
        "准备分析 Git 工作区": "Ready to Analyze Git Workspaces",
        "正在遍历可读磁盘；发现顶层仓库后不会继续下钻其内部目录。": "Scanning readable disks and stopping at each top-level repository without walking its contents.",
        "仓库定位只在本详情中运行，其他应用分析不会被重新执行。": "Repository discovery runs only in this detail view and does not reanalyze other apps.",
        "分析 Git 工作区": "Analyze Git Workspaces",
        "已包含受保护位置": "Protected Locations Included",
        "当前可读磁盘仍会继续分析；受保护目录尚未加入范围。": "Readable disks are still analyzed; protected folders are not yet included.",
        "已识别 %d 个仓库 · %d 个 Worktree": "%d repositories · %d worktrees identified",
        "统一定位本机与外接磁盘中的顶层仓库，并解析 Worktree 关系。": "Locates top-level repositories across local and external disks and resolves worktree relationships.",
        "完整仓库范围已启用": "Complete Repository Scope Enabled",
        "扩展 Git 仓库发现范围": "Expand Git Repository Discovery",
        "正在分析聊天与子代理": "Analyzing Chats and Subagents",
        "等待空间地图整体分析": "Waiting for the Full Storage Map Analysis",
        "Codex 与 Claude 深度分析由空间地图的统一分析任务生成。": "Codex and Claude deep analysis is generated by the unified Storage Map analysis.",
        "返回空间地图重新开始整体分析。": "Return to Storage Map to restart the full analysis.",
        "整体分析完成后自动显示结果": "Results appear automatically when the full analysis finishes",
        "当前分析没有此来源的结果": "No Result for This Source in the Current Analysis",
        "详情页只展示空间地图的整体分析结果，不会单独再次扫描。": "The detail view only presents results from the full Storage Map analysis and never starts a separate scan.",
        "正在分析": "Analyzing",
        "已处理 %d 项 · %@": "%d items processed · %@",
        "已分析来源组成": "Analyzed Source Composition",
        "磁盘空间构成": "Disk Storage Composition",
        "%d 块磁盘": "%d volumes",
        "文件条目": "File Entries",
        "可重建": "Rebuildable",
        "磁盘卷": "Volumes",
        "已识别": "Identified",
        "已用": "Used",
        "未识别工具占用": "No recognized tool usage",
        "已用空间归入其它": "Used space is included in Other",
        "已用 %@ / %@": "%@ used / %@",
        "可用空间": "Available",
        "其它": "Other",
        "正在建立磁盘级空间构成": "Building Disk-Level Storage Composition",
        "完成空间归属后显示各磁盘的应用、其它与可用空间": "Applications, other usage, and available space appear per disk after attribution completes",
        "Codex 与 Claude 正在独立整理聊天归属": "Codex and Claude are independently organizing chat attribution",
        "%d / %d 个来源 · %d 项 · %@": "%d / %d sources · %d items · %@",
        "刷新分析以生成磁盘级空间构成": "Refresh analysis to generate disk-level storage composition",
        "文件分配测量完成": "File Allocation Measured",
        "正在测量文件分配": "Measuring File Allocation",
        "等待调度": "Waiting to Start",
        "已确认 %d 个已知位置": "%d known locations confirmed",
        "正在分析 %d 个已知位置": "Analyzing %d known locations",
        "部分结果可用": "Partial Results Available",
        "正在等待 %@ 深度分析": "Waiting for %@ deep analysis",
        "深度分析完成": "Deep Analysis Complete",
        "聊天、全局与未归属空间已完成归因": "Chats, global data, and unattributed storage have been reconciled",
        "正在定位数据位置": "Locating Data",
        "正在进行日志数据库归因": "Attributing Log Database",
        "正在建立 %d 项聊天与子代理关系": "Building relationships for %d chats and subagents",
        "已读取 %d 条日志记录": "%d log records read",
        "已清理，等待同步确认": "Cleaned, Waiting for Sync Confirmation",
        "正在匹配 %d 条日志的聊天归属": "Matching chat ownership for %d log records",
        "正在整理聊天、全局与未归属空间": "Organizing chats, global data, and unattributed storage",
        "尚无实测数据": "No Measurements Yet",
        "等待扫描器释放并发位置": "Waiting for a scan worker",
        "尚未读取文件分配信息": "File allocation has not been read yet",
        "等待独立分析流水线开始": "Waiting for the independent analysis pipeline",
        "%d 个数据位置 · %d 个主聊天 · %d 个子代理": "%d data locations · %d main chats · %d subagents",
        "位置 %d / %d": "Location %d / %d",
        "已检查 %d 项": "%d items checked",
        "%d 个聚合类别 · 可重建候选 %@": "%d aggregate categories · %@ rebuildable candidates",
        "%d 个聚合类别 · %d 个位置读取受限": "%d aggregate categories · %d locations limited",
        "进度 %d / %d": "Progress %d / %d",
        "等待": "Waiting",
        "分析中": "Analyzing",
        "已完成": "Complete",
        "将分析 %d 个已知位置": "%d known locations will be analyzed",
        "仅读取": "Read Only",
        "正在更新": "Updating",
        "等待分析": "Waiting",
        "结果完整": "Complete",
        "部分结果": "Partial Results",
        "逻辑大小": "Logical Size",
        "文件实测候选": "File-Measured Candidates",
        "最大组成": "Largest Components",
        "本次读取范围完整": "This scan completed its full scope",
        "部分位置无法读取，容量可能偏低": "Some locations were unreadable; totals may be low",
        "开始分析后，这里会显示占用组成和数据质量。": "Storage composition and data quality appear here after analysis starts.",
        "打开 AI 工具深度分析": "Open AI Tools Deep Analysis",
        "深度分析": "Deep Analysis",
        "组成": "Component",
        "风险与状态": "Risk & Status",
        "尚未分析此来源": "This Source Has Not Been Analyzed",
        "返回空间地图开始只读分析。": "Return to Storage Map to start read-only analysis.",
        "可重建缓存": "Rebuildable Cache",
        "共享或重建成本较高": "Shared or Expensive to Rebuild",
        "环境或运行对象": "Environment or Runtime",
        "受保护数据": "Protected User Data",
        "仅分析": "Analysis Only",
        "文件实测 %@": "File measured %@",
        "扫描计划已就绪": "Scan Plan Ready",
        "建立这台 Mac 的空间地图": "Build This Mac's Storage Map",
        "%d 个来源 · %d 个已知位置": "%d sources · %d known locations",
        "上次分析未完成": "Previous Analysis Did Not Finish",
        "扫描位置分布": "Scan Location Distribution",
        "分析 %d 个位置": "Analyze %d Locations",
        "本机分析": "On-Device Analysis",
        "只读取文件元数据": "Reads File Metadata Only",
        "不执行清理动作": "No Cleanup Actions",
        "本次扫描范围": "Scan Scope",
        "按来源分组，只扫描已知位置": "Grouped by source; only known locations are scanned",
        "%d 处": "%d locations",
        "%d 个已知位置": "%d known locations",
        "只读分析": "Read-Only Analysis",
        "%d 个已知位置，只读分析": "%d known locations, read-only analysis",
        "扫描范围已确认": "Scan Scope Confirmed",
        "从已知位置开始，厘清应用、工具与运行环境的本机占用。": "Start with known locations to map local storage used by apps, tools, and runtimes.",
        "本次扫描路径": "Scan Topology",
        "连线表示扫描归属，不表示容量大小": "Connections show scan ownership, not storage size",
        "仅已知位置": "Known Locations Only",
        "本机完成": "On This Mac",
        "只读元数据": "Read-Only Metadata",
        "不执行清理": "No Cleanup",
        "开始分析 · %d 个位置": "Start Analysis · %d Locations",
        "本机只读分析，不执行清理": "Local read-only analysis with no cleanup",
        "%d 个来源 · %d 个位置": "%d sources · %d locations",
        "%d 个位置": "%d locations",
        "聊天与子代理": "Chats & Subagents",
        "%@ 聊天与子代理分析": "%@ Chats & Subagents Analysis",
        "查看 %@ 聊天与子代理": "View %@ Chats & Subagents",
        "查看专属分析": "View Tailored Analysis",
        "查看统计详情": "View Statistics",
        "分析结果完整": "Analysis Complete",
        "分析结果部分可用": "Partial Analysis Available",
        "独占占用": "Exclusive Storage",
        "其他已测占用": "Other Measured Storage",
        "聚合类别": "Aggregated Categories",
        "项": "items",
        "%d 个主聊天": "%d main chats",
        "%d 个子代理": "%d subagents",
        "分析方式": "Analysis Method",
        "进入原有的聊天、线程族与子代理深度分析，查看归属、时间和项目维度。": "Open the original deep analysis for chats, thread families, and subagents, with ownership, time, and project dimensions.",
        "区分缓存、站点数据与浏览器档案": "Separate Caches, Site Data, and Browser Profiles",
        "Chrome 的占用不等同于缓存。可重建缓存、扩展与离线站点数据、登录与浏览器档案需要分开判断。": "Chrome storage is not all cache. Rebuildable caches, extensions and offline site data, sign-in state, and browser profiles require different decisions.",
        "浏览器空间构成": "Browser Storage Composition",
        "按数据用途聚合所有已发现的 Chrome 渠道与档案，不展开浏览记录或具体站点。": "Aggregates all detected Chrome channels and profiles by purpose without exposing browsing history or individual sites.",
        "在 Chrome 中管理": "Manage in Chrome",
        "优先在 Chrome 设置中按站点检查空间。清除缓存通常可恢复；站点离线数据、扩展和档案数据可能包含登录状态与个人配置。": "Inspect storage by site in Chrome settings first. Caches are generally recoverable; offline site data, extensions, and profile data may contain sign-in state and personal settings.",
        "打开 Chrome 站点存储": "Open Chrome Site Storage",
        "看清构建缓存、模块缓存与已安装工具": "Understand Build Cache, Module Cache, and Installed Tools",
        "Go 的空间主要来自可重建的编译结果、共享模块内容和 GOPATH 中安装的命令。这里按用途汇总，不逐个展开模块或文件。": "Go storage mainly comes from rebuildable compilation results, shared modules, and commands installed in GOPATH. Results are aggregated by purpose, not by module or file.",
        "Go 使用目录级物理分配汇总：构建缓存、模块下载缓存、已解压模块和已安装工具分别测量，不在界面中逐项建立文件模型。": "Go uses directory-level physical allocation summaries. Build cache, module download cache, extracted modules, and installed tools are measured separately without building a per-file UI model.",
        "Go 工具链空间": "Go Toolchain Storage",
        "构建缓存与模块下载缓存可重新生成；已解压模块会影响后续构建速度；已安装工具是可直接使用的命令。": "Build and module download caches can be regenerated; extracted modules affect subsequent build speed; installed tools are directly usable commands.",
        "理解清理边界": "Understand Cleanup Boundaries",
        "go clean -cache 只处理构建缓存，go clean -modcache 会移除整个模块缓存并触发后续重新下载。本页仅分析，不执行命令。": "go clean -cache only handles build cache. go clean -modcache removes the entire module cache and forces later downloads. This page analyzes only and runs no commands.",
        "分开识别内容缓存、npx 临时安装与日志": "Separate Content Cache, npx Installs, and Logs",
        "npm 的全局缓存采用内容寻址存储，npx 还会留下临时安装。它们不同于项目中的 node_modules。": "npm uses content-addressed global storage, while npx may leave temporary installs. These differ from node_modules in projects.",
        "缓存通常可重新下载；npx 临时安装可重新创建；调试日志用于排查失败。项目依赖不在这里逐个展开。": "Caches can usually be downloaded again, npx installs can be recreated, and debug logs help diagnose failures. Project dependencies are not expanded here.",
        "识别跨项目复用的共享包存储": "Identify Shared Package Storage Across Projects",
        "pnpm store 会被多个项目共同引用，磁盘占用不能简单等同于某个项目的可释放空间。": "The pnpm store is shared by multiple projects, so its size is not the reclaimable space of any single project.",
        "共享包内容的重建需要重新下载，并可能影响多个工作区；索引元数据成本较低。本页不会把共享内容重复计入每个项目。": "Rebuilding shared packages requires downloads and may affect multiple workspaces; index metadata has a lower cost. Shared content is not counted once per project.",
        "区分下载缓存与全局安装": "Separate Download Cache and Global Installs",
        "Bun 同时保存可重建的包缓存与用户主动安装的全局命令，两者不应采用相同的处理方式。": "Bun stores both rebuildable package cache and user-installed global commands; they require different treatment.",
        "缓存包可重新下载；全局包代表已安装工具，移除后相关命令将不可用。本页仅展示聚合结果。": "Cached packages can be downloaded again. Global packages represent installed tools whose commands become unavailable if removed. This page shows aggregate results only.",
        "区分下载响应、Wheel 与索引元数据": "Separate Downloads, Wheels, and Index Metadata",
        "pip 缓存主要用于避免重复下载和构建，不代表当前 Python 环境中已经安装的包。": "pip cache avoids repeated downloads and builds; it does not represent packages installed in the current Python environment.",
        "HTTP 缓存和 Wheel 缓存均可重建，但下一次安装可能需要重新下载或编译；虚拟环境在工作区分析中单独汇总。": "HTTP and Wheel caches can be rebuilt, but the next install may require downloading or compiling again. Virtual environments are summarized separately under workspaces.",
        "包管理器空间": "Package Manager Storage",
        "按缓存、共享内容、临时安装或全局工具聚合，不展开每个包和文件。": "Aggregated as cache, shared content, temporary installs, or global tools without expanding individual packages and files.",
        "重建成本与作用域": "Rebuild Cost and Scope",
        "区分构建产物、源码包与开发归档": "Separate Build Products, Source Packages, and Archives",
        "Xcode 的 DerivedData 多数可重建，但归档可能包含唯一的发布记录与调试符号，不能按缓存对待。": "Most Xcode DerivedData is rebuildable, but archives may contain unique release records and debug symbols and must not be treated as cache.",
        "Xcode 开发资产": "Xcode Development Assets",
        "构建索引、中间产物、产品、源码包检出与归档按用途聚合，不展开项目文件。": "Build indexes, intermediates, products, source package checkouts, and archives are aggregated by purpose without expanding project files.",
        "保留发布资产": "Preserve Release Assets",
        "构建缓存可由 Xcode 重建；源码包重新获取需要网络；归档可能用于崩溃符号化与重新分发，应在 Xcode Organizer 中确认后管理。": "Xcode can rebuild caches; fetching source packages requires a network connection; archives may be needed for crash symbolication and redistribution and should be managed through Xcode Organizer.",
        "区分编辑器缓存、扩展与工作区状态": "Separate Editor Caches, Extensions, and Workspace State",
        "VS Code 的占用不仅来自缓存，还包含已安装扩展、用户设置、工作区状态、本地历史与未保存文件备份。": "VS Code storage includes more than caches: installed extensions, user settings, workspace state, local history, and backups of unsaved files.",
        "VS Code 空间构成": "VS Code Storage Composition",
        "按编辑器缓存、扩展安装包缓存、已安装扩展、用户与工作区状态、日志和备份分别统计。": "Measures editor caches, extension package caches, installed extensions, user and workspace state, logs, and backups separately.",
        "只清理可重建内容": "Clean Only Rebuildable Data",
        "缓存、日志与崩溃报告可以重新生成；扩展、设置、工作区状态、本地历史和未保存备份始终保持受保护。": "Caches, logs, and crash reports can be regenerated. Extensions, settings, workspace state, local history, and unsaved backups always remain protected.",
        "VS Code 用户与工作区数据": "VS Code User and Workspace Data",
        "VS Code 扩展与 CLI": "VS Code Extensions and CLI",
        "VS Code 编辑器缓存": "VS Code Editor Cache",
        "VS Code 扩展安装包缓存": "VS Code Extension Package Cache",
        "VS Code Web 缓存": "VS Code Web Cache",
        "VS Code 代码缓存": "VS Code Code Cache",
        "VS Code 图形缓存": "VS Code Graphics Cache",
        "VS Code Dawn 缓存": "VS Code Dawn Cache",
        "VS Code Graphite 缓存": "VS Code Graphite Cache",
        "VS Code WebGPU 缓存": "VS Code WebGPU Cache",
        "VS Code Profile 缓存": "VS Code Profile Cache",
        "VS Code 配置缓存": "VS Code Configuration Cache",
        "VS Code 日志": "VS Code Logs",
        "VS Code 崩溃报告": "VS Code Crash Reports",
        "VS Code 系统缓存": "VS Code System Cache",
        "VS Code 更新缓存": "VS Code Update Cache",
        "编辑器缓存": "Editor Cache",
        "图形缓存": "Graphics Cache",
        "扩展安装包缓存": "Extension Package Cache",
        "编辑器日志": "Editor Logs",
        "更新缓存": "Update Cache",
        "已安装扩展": "Installed Extensions",
        "编辑器 CLI 与配置": "Editor CLI and Configuration",
        "工作区状态": "Workspace State",
        "用户设置与扩展状态": "User Settings and Extension State",
        "本地历史与未保存备份": "Local History and Unsaved Backups",
        "扩展与 Web 状态": "Extension and Web State",
        "编辑器状态数据": "Editor State Data",
        "编辑器用户与工作区数据": "Editor User and Workspace Data",
        "已安装扩展与 CLI": "Installed Extensions and CLI",
        "VS Code 可重新生成的编辑器与 Web 缓存，不包含用户设置和工作区状态。": "Rebuildable VS Code editor and web caches that exclude user settings and workspace state.",
        "Electron 图形管线生成的 GPU、Dawn 与着色器缓存，可重新创建。": "GPU, Dawn, and shader caches generated by Electron's graphics pipeline and available to recreate.",
        "已下载的扩展安装包副本；不会移除当前已经安装的扩展。": "Downloaded extension package copies; removing them does not uninstall current extensions.",
        "VS Code 运行与扩展宿主日志，仅在排查近期问题时有保留价值。": "VS Code runtime and extension-host logs, mainly useful for investigating recent problems.",
        "VS Code 更新器留下的下载与暂存内容，可由更新器重新获取。": "Downloads and staged data left by the VS Code updater and available to fetch again.",
        "用户主动安装的扩展及其程序文件，移除后对应开发能力将不可用。": "User-installed extensions and their program files; removing them disables the associated development capabilities.",
        "VS Code 命令行组件与启动配置，不属于缓存。": "VS Code command-line components and launch configuration; these are not caches.",
        "每个工作区的编辑器状态、扩展状态与会话信息，按用户数据保护。": "Editor state, extension state, and session information for each workspace, protected as user data.",
        "包含设置、快捷键、代码片段以及扩展的全局状态。": "Contains settings, keybindings, snippets, and extension global state.",
        "可能包含尚未写回项目的内容或本地编辑历史，始终受保护。": "May contain content not yet written back to a project or local edit history and is always protected.",
        "扩展 WebView、认证和本地会话使用的数据，清除可能导致状态丢失。": "Data used by extension WebViews, authentication, and local sessions; removing it may lose state.",
        "VS Code 保存的运行状态和用户数据，未验证为缓存时一律受保护。": "VS Code runtime state and user data remain protected unless explicitly verified as cache.",
        "已安装扩展、命令行组件与启动配置，不作为普通缓存处理。": "Installed extensions, command-line components, and launch configuration are not treated as ordinary cache.",
        "分辨运行时、设备与模拟器应用数据": "Separate Runtimes, Devices, and Simulator App Data",
        "模拟器空间既包含可重新下载的系统运行时，也包含设备状态和应用测试数据，不能只看目录大小。": "Simulator storage includes downloadable system runtimes as well as device state and app test data, so directory size alone is insufficient.",
        "模拟器资产": "Simulator Assets",
        "按运行时、设备、应用数据和缓存聚合，不深入每台模拟设备的文件系统。": "Aggregated as runtimes, devices, app data, and cache without traversing each simulated device file system.",
        "通过开发工具管理": "Manage Through Developer Tools",
        "运行时应在 Xcode 的平台设置中管理；设备与应用数据应先确认测试状态。删除设备会同时移除其中的应用和数据。": "Manage runtimes in Xcode platform settings. Confirm test state before managing devices and app data; deleting a device also removes its apps and data.",
        "跟随 Docker 配置定位真实虚拟磁盘": "Follow Docker Settings to the Physical Virtual Disk",
        "自动读取 Docker Desktop 的数据目录设置，并区分当前虚拟磁盘、磁盘维护副本、日志和 Desktop 状态。": "Reads Docker Desktop's configured data location and separates the active virtual disk, maintenance copies, logs, and Desktop state.",
        "同时测量 Docker Desktop 的宿主机物理占用；Engine 可连接时，再读取镜像、容器、Volume 与构建缓存的官方容量报告。": "Measures Docker Desktop's physical host storage and, when the Engine is reachable, reads its official capacity report for images, containers, volumes, and build cache.",
        "Docker 空间构成": "Docker Storage Composition",
        "宿主机物理分配与 Engine 对象容量分开展示。镜像按 ID 去重，并区分独占、共享与总大小，避免多标签重复计数。": "Shows host physical allocation separately from Engine object sizes. Images are deduplicated by ID and split into unique, shared, and total size so multiple tags are not counted twice.",
        "按引用关系安全清理": "Clean Safely by Reference",
        "零容器引用的镜像和 Volume 可单独勾选；删除前会再次查询 Docker Engine。悬空镜像可默认安全清理，Volume 可能保存持久数据，始终由用户手动选择。": "Images and volumes with zero container references can be selected individually, and the Docker Engine is checked again before deletion. Dangling images are eligible for default safe cleanup; volumes may contain persistent data and always require manual selection.",
        "镜像、容器、卷和构建缓存共享虚拟磁盘，宿主机无法可靠拆分其内部占比。本页按真实物理位置统计，具体对象仍应在 Docker Desktop 中确认后管理。": "Images, containers, volumes, and build cache share a virtual disk that the host cannot reliably break down. This page measures its physical location; inspect and manage individual objects in Docker Desktop.",
        "磁盘检查前后保留的虚拟磁盘副本，可能用于恢复，确认 Docker 正常运行后再决定是否处理。": "Virtual-disk copies retained around a disk check may be needed for recovery. Confirm Docker is healthy before deciding whether to manage them.",
        "区分虚拟机、容器层与持久卷": "Separate Machines, Container Layers, and Persistent Volumes",
        "Podman 的机器磁盘、镜像与容器层、命名卷具有不同生命周期，命名卷尤其可能保存业务数据。": "Podman machine disks, images and container layers, and named volumes have different lifecycles; named volumes may hold application data.",
        "容器运行环境": "Container Runtime Storage",
        "展示宿主机可验证的聚合占用，不把虚拟磁盘分配量包装成可回收空间。": "Shows verifiable aggregate host storage without presenting virtual-disk allocation as reclaimable space.",
        "使用官方工具确认": "Confirm with Official Tools",
        "聚合依赖、环境与框架缓存": "Aggregate Dependencies, Environments, and Framework Caches",
        "工作区分析只区分项目文件、依赖目录、Python 环境和框架缓存，不读取源码内容，也不展开每个文件。": "Workspace analysis separates project files, dependency directories, Python environments, and framework caches without reading source content or expanding every file.",
        "工作区空间结构": "Workspace Storage Structure",
        "项目文件始终视为受保护数据；依赖和环境可能重建，但成本取决于锁文件、网络与本地工具链。": "Project files are always protected. Dependencies and environments may be rebuilt, with cost depending on lockfiles, network access, and local toolchains.",
        "在项目上下文中判断": "Decide in Project Context",
        "先确认项目是否仍在使用，并保留锁文件与环境配置。框架缓存通常可重建，但本页不会自动删除任何工作区内容。": "Confirm that the project is still in use and preserve lockfiles and environment configuration. Framework caches are generally rebuildable, but this page never deletes workspace content.",
        "本页只读分析，不会执行清理命令。": "This page is read-only and runs no cleanup commands.",
        "分析阶段只读；只有带复选框的资源可在确认后清理。": "Analysis is read-only. Only resources with checkboxes can be cleaned after confirmation.",
        "构建缓存可单独勾选并在确认后处理；模块缓存包含下载副本与已解压源码，必须整体理解其重建成本后再决定。": "Build cache can be selected and handled after confirmation. The module cache combines downloads and extracted source, so review its full rebuild cost first.",
        "缓存包可重新下载，并可在资源树中勾选后处理；全局包代表已安装工具，移除后相关命令将不可用。": "Cached packages can be downloaded again and selected in the resource tree. Global packages are installed tools whose commands become unavailable when removed.",
        "主仓库与 worktree 会按关系归组。当前仓库保持锁定；其他仓库只有在勾选并二次确认后才会移入废纸篓。": "Main repositories and worktrees are grouped by relationship. The current repository stays locked; others move to Trash only after selection and a second confirmation.",
        "分析阶段始终只读；只有带复选框的已验证资源可进入批量清理确认。": "Analysis always remains read-only. Only verified resources with checkboxes can enter batch-cleanup confirmation.",
        "确认批量清理": "Confirm Batch Cleanup",
        "批量清理结果": "Batch Cleanup Results",
        "选择此分支中的可清理资源": "Select Cleanable Resources in This Branch",
        "此资源受保护或必须通过官方工具管理": "This resource is protected or must be managed with its official tool",
        "此资源不提供直接清理": "Direct cleanup is unavailable for this resource",
        "物理分配": "Physical Allocation",
        "提供者报告": "Provider Report",
        "将使用官方工具处理 Docker 与 worktree；文件缓存和代码仓库会移入废纸篓。执行前会再次核对资源身份。": "Docker and worktrees use official tools; file caches and repositories move to Trash. Resource identities are checked again before execution.",
        "正在清理": "Cleaning",
        "资源自分析后已发生变化，请重新分析后再试。": "The resource changed after analysis. Analyze it again before retrying.",
        "当前正在使用的代码仓库不能清理。": "The repository currently in use cannot be cleaned.",
        "官方清理命令执行失败。": "The official cleanup command failed.",
        "已选择 %d 项": "%d Selected",
        "成功 %d 项，失败 %d 项": "%d succeeded, %d failed",
        "清理 %d 项": "Clean %d Items",
        "未找到 %@ 官方命令行工具。": "The official %@ command-line tool was not found.",
        "共 %@": "%@ Total",
        "聊天空间归因": "Chat Storage Attribution",
        "已可靠归属到主聊天、线程族与子代理关系的数据。": "Data reliably attributed to main chats, thread families, and subagent relationships.",
        "工具全局数据": "Tool-wide Data",
        "跨聊天共享的配置、索引与工具级数据。": "Configuration, indexes, and tool-level data shared across chats.",
        "未归属数据": "Unattributed Data",
        "已测得但无法可靠关联到某个聊天的数据，不代表可清理。": "Measured data that cannot be reliably linked to a chat; this does not imply it is safe to remove.",
        "可由浏览器重新生成，不包含浏览历史本身。": "Regenerated by the browser; this does not include browsing history itself.",
        "网站为离线使用与本地功能保存的数据，清除后可能需要重新登录或同步。": "Data stored by sites for offline and local features; removing it may require signing in or syncing again.",
        "已安装扩展及其状态，应从 Chrome 扩展管理器确认。": "Installed extensions and their state; verify them in Chrome's extension manager.",
        "包含档案配置或账户相关状态，按受保护数据处理。": "Contains profile configuration or account-related state and is treated as protected data.",
        "浏览器异常退出生成的诊断材料，可重建但可能用于问题排查。": "Diagnostics created after browser crashes; reproducible, but potentially useful for troubleshooting.",
        "Go 编译结果缓存，可重建但会增加下一次构建时间。": "Cached Go compilation results; rebuildable, but removing them increases the next build time.",
        "模块代理下载内容，可重新下载。": "Content downloaded from Go module proxies and available to download again.",
        "多个 Go 项目可共享的模块源码副本。": "Extracted module source shared by multiple Go projects.",
        "GOPATH 中已安装的命令，移除后工具将不可用。": "Commands installed in GOPATH; removing them makes those tools unavailable.",
        "npm 校验过的共享包内容，可重新下载并重新填充。": "npm's verified shared package content, which can be downloaded and populated again.",
        "npx 为临时执行保存的包环境，再次使用时可重新创建。": "Package environments retained by npx for temporary execution and recreated on later use.",
        "npm 命令失败与诊断记录，仅在排查问题时有保留价值。": "Failure and diagnostic records from npm commands, mainly useful while troubleshooting.",
        "pnpm 跨项目复用的包文件，清理会影响多个工作区的后续安装。": "Package files reused by pnpm across projects; removal affects later installs in multiple workspaces.",
        "pnpm 用于定位共享包内容的索引，可由工具重新生成。": "Indexes used by pnpm to locate shared package content and regenerated by the tool.",
        "用户主动安装的全局命令与运行环境，不属于普通下载缓存。": "User-installed global commands and runtime environments, not ordinary download cache.",
        "包管理器保存的下载内容，可重建但会产生网络与安装成本。": "Downloaded package-manager content; rebuildable with network and installation cost.",
        "pip 保存的下载响应，可重新获取，不代表环境中已安装的包。": "Download responses cached by pip; retrievable again and distinct from packages installed in environments.",
        "pip 已构建的 Wheel，可重建但可能再次消耗编译时间。": "Wheels previously built by pip; rebuildable, but potentially expensive to compile again.",
        "pip 的版本与索引检查状态，占用较小且可重新生成。": "pip version and index-check state; small and reproducible.",
        "Swift Package 依赖源码，重新获取需要网络和依赖解析。": "Swift Package dependency source; reacquisition requires network access and dependency resolution.",
        "Xcode 代码索引，可重建但会暂时影响搜索与补全。": "Xcode code indexes; rebuildable, with a temporary impact on search and completion.",
        "编译产生的中间文件，可重建但会增加下一次构建时间。": "Intermediate compiler output; rebuildable, but removing it increases the next build time.",
        "当前项目的构建输出，可能包含仍需测试或分发的产物。": "Build output from current projects that may still be needed for testing or distribution.",
        "发布归档与调试符号，可能无法从构建缓存恢复。": "Release archives and debug symbols that may not be recoverable from build cache.",
        "可从 Xcode 重新下载的系统运行时，体积大且重建依赖网络。": "System runtimes downloadable from Xcode; large and dependent on network access to restore.",
        "模拟设备的状态与配置，删除设备会连同其中数据一起移除。": "Simulator device state and configuration; deleting a device also removes its contained data.",
        "测试应用在模拟器中的文档、数据库与状态，应按用户数据判断。": "Test-app documents, databases, and state inside simulators; treat them as user data.",
        "模拟器与 CoreSimulator 生成的缓存，可重新创建。": "Caches generated by Simulator and CoreSimulator and available to recreate.",
        "承载镜像、容器、卷与构建缓存的整体磁盘，文件大小不等于可回收量。": "The aggregate disk holding images, containers, volumes, and build cache; file size is not reclaimable size.",
        "Docker Desktop 的配置与运行状态，应通过官方界面管理。": "Docker Desktop configuration and runtime state, to be managed through its official interface.",
        "容器运行日志可能用于故障排查，应结合具体容器状态判断。": "Container runtime logs may be needed for troubleshooting and should be judged with container state.",
        "Podman machine 的系统磁盘与运行环境，应由 Podman 管理生命周期。": "Podman machine system disks and runtime environments, whose lifecycle should be managed by Podman.",
        "镜像和容器共享的文件层，必须由容器引擎核对引用关系。": "Filesystem layers shared by images and containers; references must be verified by the container engine.",
        "容器持久数据，不应作为普通缓存处理。": "Persistent container data that must not be treated as ordinary cache.",
        "用户项目内容，始终受保护。": "User project content, always treated as protected.",
        "项目安装的依赖副本，能否重建取决于锁文件与包源。": "Project dependency copies; reproducibility depends on lockfiles and package sources.",
        "项目解释器与已安装包环境，重建成本取决于依赖声明和本地工具链。": "Project interpreters and installed packages; rebuild cost depends on dependency declarations and local toolchains.",
        "前端框架与构建工具生成的项目缓存，通常可重建。": "Project caches produced by frontend frameworks and build tools, generally rebuildable.",
        "按用途聚合的空间类别；请结合右侧风险标记判断重建成本。": "A usage-based storage category; use the risk indicator to judge rebuild cost.",
        "浏览器档案数据": "Browser Profile Data",
        "浏览器缓存": "Browser Cache",
        "代码缓存": "Code Cache",
        "GPU 与着色器缓存": "GPU & Shader Cache",
        "站点离线数据": "Offline Site Data",
        "扩展": "Extensions",
        "受保护浏览器数据": "Protected Browser Data",
        "崩溃报告": "Crash Reports",
        "构建缓存": "Build Cache",
        "模块下载缓存": "Module Download Cache",
        "已解压模块": "Extracted Modules",
        "已安装工具": "Installed Tools",
        "宿主机物理存储": "Host Physical Storage",
        "Docker Desktop 虚拟磁盘、维护副本、日志与状态": "Docker Desktop virtual disks, maintenance copies, logs, and state",
        "Docker Engine 资源": "Docker Engine Resources",
        "提供者报告的对象关系；镜像、容器与缓存可能共享数据层": "Provider-reported object relationships; images, containers, and caches may share data layers",
        "Docker 磁盘维护副本": "Docker Disk Maintenance Copies",
        "主仓库": "Main Repository",
        "worktree": "Worktree",
        "内容寻址缓存": "Content-Addressed Cache",
        "npx 临时安装": "Temporary npx Installs",
        "调试日志": "Debug Logs",
        "共享包内容": "Shared Package Content",
        "包索引元数据": "Package Index Metadata",
        "包缓存": "Package Cache",
        "全局包": "Global Packages",
        "缓存包": "Cached Packages",
        "HTTP 下载缓存": "HTTP Download Cache",
        "已构建 Wheel 缓存": "Built Wheel Cache",
        "索引检查元数据": "Index Check Metadata",
        "源码包检出": "Source Package Checkouts",
        "构建索引": "Build Indexes",
        "构建中间产物": "Build Intermediates",
        "构建产品": "Build Products",
        "归档": "Archives",
        "真机支持文件": "Device Support Files",
        "模拟器运行时": "Simulator Runtimes",
        "模拟器应用数据": "Simulator App Data",
        "模拟器设备": "Simulator Devices",
        "按具体设备名称与 Runtime 展示": "Listed by exact device and runtime name",
        "按已安装 Runtime 名称展示": "Listed by installed runtime name",
        "系统下载资源": "System-downloaded asset",
        "系统安装": "System-installed",
        "用户安装": "User-installed",
        "正在创建": "Creating",
        "已关机": "Shut Down",
        "正在启动": "Booting",
        "已启动": "Booted",
        "正在关机": "Shutting Down",
        "模拟器缓存": "Simulator Cache",
        "模拟器待删除数据": "Pending Simulator Deletion",
        "Simulator devices": "Simulator Devices",
        "Simulator user caches": "Simulator User Caches",
        "Simulator pending deletion": "Pending Simulator Deletion",
        "User-installed Simulator runtimes": "User-installed Simulator Runtimes",
        "Legacy Simulator runtimes": "Legacy Simulator Runtimes",
        "Simulator shared caches": "Simulator Shared Caches",
        "Downloaded Simulator runtimes": "Downloaded Simulator Runtimes",
        "Simulator 与 Simulator Runtime 是两类资产：前者保存设备和测试应用数据，后者是可重新下载的系统镜像；共享缓存与待删除数据也会单独统计。": "Simulators and Simulator Runtimes are different assets: simulators hold device and test-app data, while runtimes are downloadable system images. Shared caches and pending deletion data are measured separately.",
        "按设备、应用数据、Runtime 镜像、共享缓存和后台待删数据聚合。只统计 Runtime 的宿主机 backing storage，不重复统计只读挂载卷。": "Grouped into devices, app data, runtime images, shared caches, and pending background deletion. Runtime usage counts host backing storage only, without double-counting read-only mounted volumes.",
        "CoreSimulator 已安排后台移除的残留数据，通常会由系统继续清理。": "Residual data already scheduled for background removal by CoreSimulator; the system normally continues cleaning it.",
        "%d 个": "%d",
        "已知位置": "Known Locations",
        "返回": "Back",
        "理解这个来源的空间构成": "Understand This Source's Storage",
        "按用途聚合已测得的本机空间，不展开文件内容。": "Groups measured local storage by purpose without exposing file contents.",
        "空间构成": "Storage Composition",
        "仅显示已知位置的文件分配占用。": "Shows file allocation only for known locations.",
        "分析边界": "Analysis Boundary",
        "聊天与子代理分析": "Chat and Subagent Analysis",
        "按聊天、线程族与子代理关系分析占用。": "Analyzes storage by chats, thread families, and subagent relationships.",
        "虚拟机和容器层需要由 Podman 了解内部引用关系；命名卷属于持久数据。本页不会依据文件树猜测可删除对象。": "Podman must resolve internal references for machines and container layers. Named volumes are persistent data, and this view never guesses deletable objects from the file tree.",
        "Docker 虚拟磁盘": "Docker Virtual Disk",
        "容器日志": "Container Logs",
        "Docker Desktop 状态": "Docker Desktop State",
        "Podman 虚拟机": "Podman Machines",
        "镜像与容器层": "Images & Container Layers",
        "命名卷": "Named Volumes",
        "项目文件": "Project Files",
        "依赖目录": "Dependency Directories",
        "Python 环境": "Python Environments",
        "框架缓存": "Framework Caches",
        "代码仓库内容": "Repository Content",
        "Worktree 内容": "Worktree Content",
        "主仓库中的源码、版本历史与项目资产，按受保护数据处理。": "Source, version history, and project assets in the main repository are treated as protected data.",
        "共享主仓库 Git 数据但拥有独立工作目录与分支状态。": "Shares Git data with the main repository while keeping an independent working directory and branch state."
    ]
}

enum AppResourceBundle {
    static var value: Bundle {
        #if SWIFT_PACKAGE
        .module
        #else
        .main
        #endif
    }
}
